data:
  batch_size: 64
  shuffle: True
  num_workers: 2
  mode: "subtract"
  p_quant: 128
  window_len: 128
  random_seed: 42
training:
  num_epochs: 20
  lr: 0.001
  min_lr: 0.0005
  weight_decay:  0.00005
model:
  model_dir: "saved_models"
  name: "ConvNeXt_tiny"
  dropout: 0.5
