data:
  batch_size: 256
  shuffle: True
  num_workers: 2
  mode: "subtract"
  p_quant: 112
  window_len: 112
  random_seed: 42
  space_between: 0
  enlarge_factor: 1
  interpolation_factor: 2
  offset: 1
training:
  num_epochs: 20
  lr: 0.0001
  min_lr: 0.0001
  weight_decay:  0.
model:
  model_dir: "saved_models"
  name: "VIT_b_16"
  dropout: 0.5
